'use client';

import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import {
    LuX,
    LuSparkles,
    LuLoader,
    LuCheck,
    LuSave,
    LuArrowRight,
    LuArrowLeft,
    LuPlus,
    LuBook
} from 'react-icons/lu';
import styles from './ai-generator-modal.module.css';
import { aiService, GeneratedCard } from '@/lib/ai-service';
import { createDeck, getUserDecks } from '@/lib/decks';
import { createCard } from '@/lib/cards';
import { useAuth } from '@/lib/auth-context';
import { Deck } from '@/types/decks';

interface AIGeneratorModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess?: (deckId: string) => void;
    // Props for backward compatibility / deck-specific context
    deckId?: string;
    onCardsAdded?: () => void;
}

type Step = 'input' | 'generating' | 'preview';

export function AIGeneratorModal({ isOpen, onClose, onSuccess, deckId, onCardsAdded }: AIGeneratorModalProps) {
    const { user } = useAuth();
    const [step, setStep] = useState<Step>('input');
    const [topic, setTopic] = useState('');
    const [generatedCards, setGeneratedCards] = useState<GeneratedCard[]>([]);
    const [userDecks, setUserDecks] = useState<Deck[]>([]);

    // Save options
    const [saveMode, setSaveMode] = useState<'existing' | 'new'>('new');
    const [selectedDeckId, setSelectedDeckId] = useState('');
    const [newDeckTitle, setNewDeckTitle] = useState('');
    const [isSaving, setIsSaving] = useState(false);

    // Reset state when opening
    useEffect(() => {
        if (isOpen) {
            setStep('input');
            setTopic('');
            setGeneratedCards([]);
            setNewDeckTitle('');

            // If generated within a specific deck context
            if (deckId) {
                setSaveMode('existing');
                setSelectedDeckId(deckId);
            } else {
                setSaveMode('new');
                setSelectedDeckId('');
            }

            fetchUserDecks();
        }
    }, [isOpen, deckId]);

    const fetchUserDecks = async () => {
        if (!user) return;
        try {
            const decks = await getUserDecks(user.id);
            setUserDecks(decks);
        } catch (error) {
            console.error('Failed to fetch decks:', error);
        }
    };

    const handleGenerate = async () => {
        if (!topic.trim()) return;

        setStep('generating');
        try {
            const cards = await aiService.generateFlashcards(topic);
            setGeneratedCards(cards);
            if (!deckId) {
                setNewDeckTitle(topic); // Default new deck title to topic only if not in deck context
            }
            setStep('preview');
        } catch (error: any) {
            console.error('Generation failed:', error);
            setStep('input');
            // Show specific error message from backend if available
            const errorMessage = error.message || '生成失败，请稍后重试';
            alert(errorMessage);
        }
    };

    const handleSave = async () => {
        if (!user) return;
        if (saveMode === 'new' && !newDeckTitle.trim()) return;
        if (saveMode === 'existing' && !selectedDeckId) return;

        setIsSaving(true);
        try {
            let targetDeckId = selectedDeckId;

            // 1. Create Deck if needed
            if (saveMode === 'new') {
                const newDeck = await createDeck(user.id, {
                    title: newDeckTitle,
                    description: `Generated by AI for topic: ${topic}`,
                    is_public: false,
                    tags: ['AI-Generated']
                });
                targetDeckId = newDeck.id;
            }

            // 2. Add Cards
            await Promise.all(generatedCards.map(card =>
                createCard({
                    deck_id: targetDeckId,
                    front: card.front,
                    back: card.back,
                    state: 'new'
                })
            ));

            // 3. Success callbacks
            if (onSuccess) onSuccess(targetDeckId);
            if (onCardsAdded) onCardsAdded();

            onClose();

        } catch (error) {
            console.error('Save failed:', error);
            alert('保存失败');
        } finally {
            setIsSaving(false);
        }
    };

    if (!isOpen) return null;

    return createPortal(
        <div className={styles.overlay}>
            <div className={styles.container}>
                {/* Header */}
                <div className={styles.header}>
                    <div className={styles.headerTitle}>
                        {step !== 'input' && (
                            <button
                                onClick={() => setStep('input')}
                                className={styles.backBtn}
                                title="返回"
                            >
                                <LuArrowLeft size={20} />
                            </button>
                        )}
                        <div className={styles.iconBox}>
                            <LuSparkles size={20} />
                        </div>
                        <h3>AI 闪卡生成</h3>
                    </div>
                    <button onClick={onClose} className={styles.closeBtn}>
                        <LuX size={20} />
                    </button>
                </div>

                {/* Body */}
                <div className={styles.body}>
                    {step === 'input' && (
                        <div className={styles.inputStep}>
                            <h4 className={styles.stepTitle}>你想学习什么？</h4>
                            <p className={styles.stepDesc}>输入主题、概念或书籍名称，AI 将为你提取核心知识点。</p>
                            <div className={styles.inputWrapper}>
                                <input
                                    type="text"
                                    value={topic}
                                    onChange={(e) => setTopic(e.target.value)}
                                    placeholder="例如：光合作用原理、React Hooks、二战历史..."
                                    className={styles.topicInput}
                                    autoFocus
                                    onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                                />
                                <button
                                    onClick={handleGenerate}
                                    disabled={!topic.trim()}
                                    className={styles.primaryBtn}
                                >
                                    <LuSparkles size={18} />
                                    <span>开始生成</span>
                                </button>
                            </div>
                            <div className={styles.suggestions}>
                                <span>热门尝试：</span>
                                {['商务英语', 'Python 基础', '心理学效应', '世界地理'].map(t => (
                                    <button key={t} onClick={() => setTopic(t)} className={styles.tag}>{t}</button>
                                ))}
                            </div>
                        </div>
                    )}

                    {step === 'generating' && (
                        <div className={styles.generatingStep}>
                            <div className={styles.loaderWrapper}>
                                <LuLoader size={48} className={styles.spinner} />
                            </div>
                            <h4>正在深入分析知识网络...</h4>
                            <p>AI 正在为你整理 "{topic}" 的核心考点</p>
                        </div>
                    )}

                    {step === 'preview' && (
                        <div className={styles.previewStep}>
                            <div className={styles.previewHeader}>
                                <h4>
                                    <LuCheck size={18} className={styles.successIcon} />
                                    已生成 {generatedCards.length} 张卡片
                                </h4>

                                {/* Only show save options if NOT locked to a deck */}
                                {!deckId && (
                                    <div className={styles.saveOptions}>
                                        <div className={styles.toggleGroup}>
                                            <button
                                                className={`${styles.toggleBtn} ${saveMode === 'new' ? styles.active : ''}`}
                                                onClick={() => setSaveMode('new')}
                                            >
                                                <LuPlus size={14} /> 新建牌组
                                            </button>
                                            <button
                                                className={`${styles.toggleBtn} ${saveMode === 'existing' ? styles.active : ''}`}
                                                onClick={() => setSaveMode('existing')}
                                            >
                                                <LuBook size={14} /> 现有牌组
                                            </button>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Cards List */}
                            <div className={styles.cardsList}>
                                {generatedCards.map((card, i) => (
                                    <div key={i} className={styles.miniCard}>
                                        <div className={styles.cardFront}>
                                            <span className={styles.label}>Q</span>
                                            <p>{card.front}</p>
                                        </div>
                                        <div className={styles.divider} />
                                        <div className={styles.cardBack}>
                                            <span className={styles.label}>A</span>
                                            <p>{card.back}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Save Form */}
                            <div className={styles.saveForm}>
                                {saveMode === 'new' ? (
                                    <input
                                        type="text"
                                        value={newDeckTitle}
                                        onChange={(e) => setNewDeckTitle(e.target.value)}
                                        placeholder="输入牌组名称"
                                        className={styles.saveInput}
                                    />
                                ) : (
                                    <select
                                        value={selectedDeckId}
                                        onChange={(e) => setSelectedDeckId(e.target.value)}
                                        className={styles.saveSelect}
                                        disabled={!!deckId} // Disable selection if locked to a deck
                                    >
                                        <option value="">选择一个牌组...</option>
                                        {userDecks.map(d => (
                                            <option key={d.id} value={d.id}>{d.title}</option>
                                        ))}
                                    </select>
                                )}

                                <button
                                    onClick={handleSave}
                                    disabled={isSaving || (saveMode === 'new' && !newDeckTitle) || (saveMode === 'existing' && !selectedDeckId)}
                                    className={styles.saveBtn}
                                >
                                    {isSaving ? <LuLoader className={styles.spinner} /> : <LuSave />}
                                    保存{deckId ? '到当前牌组' : '并开始学习'}
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>,
        document.body
    );
}
